### PR TITLE
WIP: Memory leaks

### PR DESCRIPTION
**Pull request by tyldum**
Possible fix for #7 
More testing is needed to see if they fix the real problem, but nothing seems broken and my initial tests were good.

### CODE REVIEW

**Comment by tyldum** [comment]
Still leaks, needs more. It's the queue array that simply grows.

**Comment by dotandimet** [comment]
I think that's just how Perl arrays behave (shift doesn't shorten it).
Does the queue ever empty? If so, maybe we can reset it i.e, $self->jobs([]) once that happens?

**Comment by tyldum** [comment]
Seems to grow forever, I can give that a try.

**Comment by tyldum** [comment]
That did not change anything. Array still grows. The "queue_empty" event is fired.
I think maybe I need a more minimal code to test on.

**Comment by tyldum** [comment]
The changes made for 1.14 seems to fix all leaks I was seeing (about 12k/s). Nice work! Thank you!
Closing this PR, as it is obsolete.

**Pull request closed without merging**
